// Seed data based on the room data provided
const roomsData = [
  // Gedung K
  { gedung: 'K', ruang: 'K.101', kapasitas: 40, deskripsi: 'Classroom', fasilitas: ['Projector', 'Whiteboard'], status: 'tersedia' },
  { gedung: 'K', ruang: 'K.102', kapasitas: 80, deskripsi: 'Lecture Hall', fasilitas: ['Projector', 'Speaker System'], status: 'tersedia' },
  { gedung: 'K', ruang: 'K.103', kapasitas: 80, deskripsi: 'Classroom', fasilitas: ['Projector', 'Whiteboard'], status: 'tersedia' },
  { gedung: 'K', ruang: 'K.104', kapasitas: 50, deskripsi: 'Seminar Room', fasilitas: ['Projector'], status: 'tersedia' },
  { gedung: 'K', ruang: 'K.105', kapasitas: 50, deskripsi: 'Classroom', fasilitas: ['Whiteboard'], status: 'tersedia' },
  { gedung: 'K', ruang: 'K.106', kapasitas: 80, deskripsi: 'Lecture Hall', fasilitas: ['Projector', 'Speaker System'], status: 'tersedia' },
  { gedung: 'K', ruang: 'K.107', kapasitas: 80, deskripsi: 'Classroom', fasilitas: ['Projector', 'Whiteboard'], status: 'tersedia' },
  { gedung: 'K', ruang: 'K.108', kapasitas: 50, deskripsi: 'Seminar Room', fasilitas: ['Projector'], status: 'tersedia' },
  { gedung: 'K', ruang: 'K.201', kapasitas: 45, deskripsi: 'Classroom', fasilitas: ['Projector', 'Whiteboard'], status: 'tersedia' },
  { gedung: 'K', ruang: 'K.202', kapasitas: 80, deskripsi: 'Lecture Hall', fasilitas: ['Projector', 'Speaker System'], status: 'tersedia' },
  { gedung: 'K', ruang: 'K.203', kapasitas: 42, deskripsi: 'Classroom', fasilitas: ['Projector', 'Whiteboard'], status: 'tersedia' },
  { gedung: 'K', ruang: 'K.204', kapasitas: 80, deskripsi: 'Lecture Hall', fasilitas: ['Projector', 'Speaker System'], status: 'tersedia' },
  { gedung: 'K', ruang: 'K.205', kapasitas: 30, deskripsi: 'Small Seminar Room', fasilitas: ['Whiteboard'], status: 'tersedia' },
  { gedung: 'K', ruang: 'K.206', kapasitas: 100, deskripsi: 'Large Lecture Hall', fasilitas: ['Projector', 'Speaker System', 'Advanced AV'], status: 'tersedia' },
  { gedung: 'K', ruang: 'K.207', kapasitas: 80, deskripsi: 'Lecture Hall', fasilitas: ['Projector', 'Speaker System'], status: 'tersedia' },
  { gedung: 'K', ruang: 'K.208', kapasitas: 40, deskripsi: 'Classroom', fasilitas: ['Projector', 'Whiteboard'], status: 'tersedia' },
  { gedung: 'K', ruang: 'K.209', kapasitas: 80, deskripsi: 'Lecture Hall', fasilitas: ['Projector', 'Speaker System'], status: 'tersedia' },
  { gedung: 'K', ruang: 'K.210', kapasitas: 70, deskripsi: 'Classroom', fasilitas: ['Projector', 'Whiteboard'], status: 'tersedia' },
  { gedung: 'K', ruang: 'K.211', kapasitas: 80, deskripsi: 'Lecture Hall', fasilitas: ['Projector', 'Speaker System'], status: 'tersedia' },
  { gedung: 'K', ruang: 'K.301', kapasitas: 200, deskripsi: 'Large Conference Hall', fasilitas: ['Projector', 'Speaker System', 'Advanced AV', 'Conference Setup'], status: 'tersedia' },
  { gedung: 'K', ruang: 'K.Lobi', kapasitas: 100, deskripsi: 'Lobby/Common Area', fasilitas: ['Seating'], status: 'tersedia' },

  // Gedung S
  { gedung: 'S', ruang: 'S.101', kapasitas: 70, deskripsi: 'Classroom', fasilitas: ['Projector', 'Whiteboard'], status: 'tersedia' },
  { gedung: 'S', ruang: 'S.102', kapasitas: 70, deskripsi: 'Classroom', fasilitas: ['Projector', 'Whiteboard'], status: 'tersedia' },
  { gedung: 'S', ruang: 'S.103', kapasitas: 40, deskripsi: 'Small Classroom', fasilitas: ['Whiteboard'], status: 'tersedia' },
  { gedung: 'S', ruang: 'S.201', kapasitas: 50, deskripsi: 'Seminar Room', fasilitas: ['Projector'], status: 'tersedia' },
  { gedung: 'S', ruang: 'S.202', kapasitas: 70, deskripsi: 'Classroom', fasilitas: ['Projector', 'Whiteboard'], status: 'tersedia' },
  { gedung: 'S', ruang: 'S.203', kapasitas: 70, deskripsi: 'Classroom', fasilitas: ['Projector', 'Whiteboard'], status: 'tersedia' },
  { gedung: 'S', ruang: 'S.204', kapasitas: 40, deskripsi: 'Small Classroom', fasilitas: ['Whiteboard'], status: 'tersedia' },
  { gedung: 'S', ruang: 'S.205', kapasitas: 70, deskripsi: 'Classroom', fasilitas: ['Projector', 'Whiteboard'], status: 'tersedia' },
  { gedung: 'S', ruang: 'S.301', kapasitas: 40, deskripsi: 'Seminar Room', fasilitas: ['Projector'], status: 'tersedia' },
  { gedung: 'S', ruang: 'S.302', kapasitas: 70, deskripsi: 'Classroom', fasilitas: ['Projector', 'Whiteboard'], status: 'tersedia' },
  { gedung: 'S', ruang: 'S.303', kapasitas: 40, deskripsi: 'Small Classroom', fasilitas: ['Whiteboard'], status: 'tersedia' },
  { gedung: 'S', ruang: 'S.304', kapasitas: 70, deskripsi: 'Classroom', fasilitas: ['Projector', 'Whiteboard'], status: 'tersedia' },
  { gedung: 'S', ruang: 'S.305', kapasitas: 70, deskripsi: 'Classroom', fasilitas: ['Projector', 'Whiteboard'], status: 'tersedia' },
  { gedung: 'S', ruang: 'S.401', kapasitas: 60, deskripsi: 'Classroom', fasilitas: ['Projector', 'Whiteboard'], status: 'tersedia' },
  { gedung: 'S', ruang: 'S.402', kapasitas: 80, deskripsi: 'Lecture Hall', fasilitas: ['Projector', 'Speaker System'], status: 'tersedia' },
  { gedung: 'S', ruang: 'S.403', kapasitas: 45, deskripsi: 'Seminar Room', fasilitas: ['Projector'], status: 'tersedia' },
  { gedung: 'S', ruang: 'S.404', kapasitas: 60, deskripsi: 'Classroom', fasilitas: ['Projector', 'Whiteboard'], status: 'tersedia' },
  { gedung: 'S', ruang: 'S.405', kapasitas: 100, deskripsi: 'Large Lecture Hall', fasilitas: ['Projector', 'Speaker System', 'Advanced AV'], status: 'tersedia' },
  { gedung: 'S', ruang: 'S.501', kapasitas: 45, deskripsi: 'Seminar Room', fasilitas: ['Projector'], status: 'tersedia' },
  { gedung: 'S', ruang: 'S.502', kapasitas: 90, deskripsi: 'Large Classroom', fasilitas: ['Projector', 'Whiteboard', 'Speaker System'], status: 'tersedia' },
  { gedung: 'S', ruang: 'S.503 (Studio Gbr)', kapasitas: 80, deskripsi: 'Design Studio with Drawing Boards', fasilitas: ['Projector', 'Drawing Boards', 'Natural Lighting'], status: 'tersedia' },
  { gedung: 'S', ruang: 'S.504', kapasitas: 90, deskripsi: 'Large Classroom', fasilitas: ['Projector', 'Whiteboard', 'Speaker System'], status: 'tersedia' },

  // Gedung GK
  { gedung: 'GK', ruang: 'GK.302', kapasitas: 20, deskripsi: 'Small Lab/Workshop', fasilitas: ['Equipment'], status: 'tersedia' },
  { gedung: 'GK', ruang: 'GK.303', kapasitas: 30, deskripsi: 'Lab/Workshop', fasilitas: ['Equipment', 'Workstations'], status: 'tersedia' },
  { gedung: 'GK', ruang: 'GK.304', kapasitas: 30, deskripsi: 'Lab/Workshop', fasilitas: ['Equipment', 'Workstations'], status: 'tersedia' },
  { gedung: 'GK', ruang: 'GK.305', kapasitas: 30, deskripsi: 'Lab/Workshop', fasilitas: ['Equipment', 'Workstations'], status: 'tersedia' },
  { gedung: 'GK', ruang: 'GK.306', kapasitas: 100, deskripsi: 'Large Lab/Workshop', fasilitas: ['Equipment', 'Workstations', 'Power Supply'], status: 'tersedia' },
  { gedung: 'GK', ruang: 'GK.201', kapasitas: 40, deskripsi: 'Lab/Workshop', fasilitas: ['Equipment', 'Workstations'], status: 'tersedia' },
  { gedung: 'GK', ruang: 'GK.207', kapasitas: 54, deskripsi: 'Lab/Workshop', fasilitas: ['Equipment', 'Workstations'], status: 'tersedia' },

  // Area Lain (Other Areas)
  { gedung: 'Area Lain', ruang: 'Area L. Futsal Dekanat', kapasitas: 100, deskripsi: 'Futsal Court - Dean Office Area', fasilitas: ['Court Lines', 'Goals'], status: 'tersedia' },
  { gedung: 'Area Lain', ruang: 'Area L. Voli GK', kapasitas: 100, deskripsi: 'Volleyball Court - GK Area', fasilitas: ['Net', 'Court Lines'], status: 'tersedia' },
  { gedung: 'Area Lain', ruang: 'Area L. Basket Kantek', kapasitas: 100, deskripsi: 'Basketball Court - Kantek', fasilitas: ['Hoop', 'Court Lines'], status: 'tersedia' },
  { gedung: 'Area Lain', ruang: 'Area Taman BP3', kapasitas: 100, deskripsi: 'Garden/Park Area BP3', fasilitas: ['Outdoor Space', 'Seating'], status: 'tersedia' },
  { gedung: 'Area Lain', ruang: 'Area Taman Rotunda', kapasitas: 50, deskripsi: 'Rotunda Garden Area', fasilitas: ['Outdoor Space', 'Seating'], status: 'tersedia' },
  { gedung: 'Area Lain', ruang: 'Area Kantin', kapasitas: 50, deskripsi: 'Cafeteria/Canteen Area', fasilitas: ['Dining', 'Seating'], status: 'tersedia' },
  { gedung: 'Area Lain', ruang: 'Lobi Gedung EC', kapasitas: 50, deskripsi: 'EC Building Lobby', fasilitas: ['Seating', 'Information Desk'], status: 'tersedia' },
  { gedung: 'Area Lain', ruang: 'Kantin Dalam', kapasitas: 50, deskripsi: 'Indoor Cafeteria', fasilitas: ['Dining', 'Seating'], status: 'tersedia' },
  { gedung: 'Area Lain', ruang: 'Kantin Bawah', kapasitas: 50, deskripsi: 'Lower Cafeteria', fasilitas: ['Dining', 'Seating'], status: 'tersedia' },
  { gedung: 'Area Lain', ruang: 'Kantin Atas', kapasitas: 50, deskripsi: 'Upper Cafeteria', fasilitas: ['Dining', 'Seating'], status: 'tersedia' },
  { gedung: 'Area Lain', ruang: 'Taman Depan Gedung BP3', kapasitas: 50, deskripsi: 'Front Garden BP3 Building', fasilitas: ['Outdoor Space', 'Seating'], status: 'tersedia' },
  { gedung: 'Area Lain', ruang: 'Taman Dekat Rotunda', kapasitas: 50, deskripsi: 'Garden Near Rotunda', fasilitas: ['Outdoor Space', 'Seating'], status: 'tersedia' },
  { gedung: 'Area Lain', ruang: 'Taman Gedung EC', kapasitas: 50, deskripsi: 'EC Building Garden', fasilitas: ['Outdoor Space', 'Seating'], status: 'tersedia' },
];

module.exports = roomsData;
